import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Minor Questions",
	description: "Generated by create next app",
};

const pretendard = localFont({
	name: "pretendard",
	src: [
		{
			path: "fonts/PretendardVariable.woff2",
			weight: "400 500 600",
		},
	],
});

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
				/>
			</head>
			<body className={`${pretendard.variable} font-global font-normal`}>
				{children}
			</body>
		</html>
	);
}
